import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Sidebar from '@/components/sidebar'
import { useUser } from '@auth0/nextjs-auth0/client';

export default function Home() {
  const { user, error, isLoading } = useUser();
  return (
    <>
      <Head>
        <title>Team Undefined</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex justify-center items-center h-screen'>
        <div className=' container bg-gray-300 w-60 h-80 drop-shadow-lg flex justify-center items-center flex-col'>
          <a href="/api/auth/login">Login</a>
          <a href="/jhopkins/appointments">Doctor View</a>
          <a href="/bavaria/reports">Bavaria</a>
          <a href="/fda/liveresults">FDA View</a>
          {/* <p>{user.email}</p> */}
        </div>
      </main>
    </>
  )
}
