import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Sidebar from '@/components/Sidebar';
import { useUser } from '@auth0/nextjs-auth0/client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Pfizer from '../../public/pfizer-mono.png';
import Moderna from '../../public/moderna-mono.png';
import Fda from '../../public/fda.png';
import JAndJ from '../../public/jandj-mono.png';
import Abbvie from '../../public/abbvie-mono.png';
import Lock from '@/components/icons/Lock';
import Cloud from '@/components/icons/Cloud';
import Enterprise from '@/components/icons/Enterprise';
import Logo from '@/components/icons/Logo';
export default function Home() {
	const { user, error, isLoading } = useUser();

	return (
		<>
			<Head>
				<title>Team Undefined</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<header className="sticky top-0 z-50 bg-white shadow-md shadow-slate-900/5">
				<div className="inner-column py-2">
					<nav className="flex flex-row items-center justify-between">
						<div className="max-w-[50px]">
							<Logo />
						</div>
						<div className="">{renderContent({ user, error, isLoading })}</div>
					</nav>
				</div>
			</header>
			<main className="flex-1">
				<section className="bg-slate-50 pt-40 pb-20">
					<div className="inner-column">
						<div className="flex flex-col items-center justify-center">
							<h1 className="title-voice max-w-prose text-center leading-tight tracking-tight">
								PharmaStudy, a{' '}
								<span className="bg-gradient-to-r from-indigo-200 via-sky-400 to-indigo-200 bg-clip-text text-transparent">
									better
								</span>{' '}
								way to run pharmaceutical studies
							</h1>
							<p className="mt-6 text-center text-2xl">
								Meet the new standard for modern medicine. <br />
								Streamline studies, tracking, and safety.
							</p>

							<div className="mt-8">
								<Link
									href="/api/auth/login"
									className="group inline-flex items-center justify-center rounded-full bg-slate-900 py-2 px-4 text-base font-semibold text-white hover:bg-slate-700 hover:text-slate-100 focus:outline-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-slate-900 active:bg-slate-800 active:text-slate-300"
								>
									Get started
								</Link>
							</div>
						</div>
					</div>
				</section>

				<section className="bg-slate-50 py-4 pb-12">
					<div className="inner-column">
						<h2 className="text-center text-sm font-bold uppercase tracking-wider">
							1,000 pharmaceutical and research companies trust PharmaStudy
						</h2>
						<div className="mt-6 flex flex-row justify-center gap-4">
							<div className="flex max-w-[150px] items-center rounded-lg border py-4 px-7">
								<Image src={Moderna} className=""></Image>
							</div>
							<div className="flex max-w-[150px] items-center rounded-lg border py-4 px-7">
								<Image src={Pfizer} className=""></Image>
							</div>
							<div className="flex max-w-[150px] items-center rounded-lg border py-4 px-7">
								<Image src={Fda} className=""></Image>
							</div>
							<div className="flex max-w-[150px] items-center rounded-lg border py-4 px-7">
								<Image src={JAndJ} className=""></Image>
							</div>

							<div className="flex max-w-[150px] items-center rounded-lg border py-4 px-7">
								<Image src={Abbvie} className=""></Image>
							</div>
						</div>
					</div>
				</section>

				<section className="py-28">
					<div className="inner-column">
						<div>
							<h2 className="attention-voice max-w-[18ch]">Unlike any tool you’ve used before</h2>
							<p className="mt-8 max-w-prose">
								Other pharmaceutical software allows you to track your patients, view the results, and
								other things you expect. PharmaStudy offers the typical features you expect, but is also
								different in some key areas…
							</p>
						</div>

						<div className="mt-16 grid grid-cols-3 gap-16">
							<div>
								<div className="relative flex h-14 w-14 items-center justify-center rounded-full border border-sky-400 border-opacity-20 before:absolute  before:top-1/2 before:left-1/2 before:z-10 before:h-20 before:w-20 before:-translate-x-1/2 before:-translate-y-1/2 before:rounded-full before:bg-sky-500 before:opacity-10 before:blur-lg">
									<Lock />
								</div>
								<h3 className="calm-voice mt-6">A focus on privacy</h3>
								<p className="my-4 max-w-prose leading-relaxed">
									A single source of truth to your pharmaceutical studies. Secure, compliant, and real
									time collaboration with every participant in the study. Everyone works with the same
									set of data, but PII best practices are followed to ensure no bias, HIPA compliance.
								</p>
							</div>
							<div>
								<div className="relative flex h-14 w-14 items-center justify-center rounded-full border border-violet-400 border-opacity-20 before:absolute  before:top-1/2 before:left-1/2 before:z-10 before:h-20 before:w-20 before:-translate-x-1/2 before:-translate-y-1/2 before:rounded-full before:bg-violet-500 before:opacity-10 before:blur-lg">
									<Cloud />
								</div>
								<h3 className="calm-voice mt-6">A modern cloud based app</h3>
								<p className="my-4 max-w-prose leading-relaxed">
									This isn’t a 30 year old software on its last legs. PharmaStudy is a modern cloud
									based application leverageing modern standards in tech to bring real-time data
									sharing.
								</p>
							</div>
							<div>
								<div className="relative flex h-14 w-14 items-center justify-center rounded-full border border-emerald-400 border-opacity-20 before:absolute  before:top-1/2 before:left-1/2 before:z-10 before:h-20 before:w-20 before:-translate-x-1/2 before:-translate-y-1/2 before:rounded-full before:bg-emerald-500 before:opacity-10 before:blur-lg">
									<Enterprise />
								</div>
								<h3 className="calm-voice mt-6">Enterprise ready</h3>
								<p className="my-4 max-w-prose leading-relaxed">
									A single source of truth to your pharmaceutical studies. Secure, compliant, and real
									time collaboration. Everyone works with the same set of data, but PII best practices
									are followed to ensure no bias and HIPA compliance.
								</p>
							</div>
						</div>
					</div>
				</section>
			</main>
			<footer>
				<h2>footer</h2>
			</footer>
		</>
	);
}

function renderContent({ user, error, isLoading }) {
	if (isLoading) {
		return <div>Loading...</div>;
	}
	if (error) {
		return <div>Oops... {error.message}</div>;
	}
	if (user) {
		return (
			<>
				{/* <span onClick={console.log(user)} className="block text-right">{`${user.name}`}</span> */}
				<ul className="mt-2 flex flex-row gap-4">
					<li>
						<Link href="/api/auth/logout" className="btn-outline btn-sm btn">
							Logout
						</Link>
					</li>
					<li>
						<Link href={'/redirect'} className="btn-sm btn">
							Go to Dashboard
						</Link>
					</li>
				</ul>
			</>
		);
	} else {
		return (
			<ul>
				<li>
					<Link
						href="/api/auth/login"
						className="inline-flex hidden justify-center rounded-lg bg-gray-800 py-2 px-3 text-sm font-semibold text-white outline-2 outline-offset-2 transition-colors hover:bg-gray-900 active:bg-gray-800 active:text-white/80 lg:block"
					>
						Login
					</Link>
				</li>
			</ul>
		);
	}
}
