import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Sidebar from '@/components/Sidebar';
import { useUser } from '@auth0/nextjs-auth0/client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
export default function Home() {
	const { user, error, isLoading } = useUser();
	let href_path;

	if (isLoading) {
		return <div>Loading...</div>;
	}
	if (error) {
		return <div>Oops... {error.message}</div>;
	}
	if (user) {
		if (user.role == 'doctor') {
			href_path = 'jhopkins/my-patients';
		} else if (user.role == 'fda') {
			href_path = 'fda/live-results';
		} else if (user.role == 'bavaria') {
			href_path = 'bavaria/reports';
		} else if (user.role == 'admin') {
			href_path = 'admin/all-patients';
		}
		return (
			<>
				<Head>
					<title>Team Undefined</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main className="flex justify-center items-center h-screen">
					<div className=" container bg-gray-300 w-60 h-80 drop-shadow-lg flex justify-center items-center flex-col">
						<span onClick={console.log(user)}>{`Logged in as ${user.name}`}</span>
						<Link href={href_path} className="p-2 border-2 border-black hover:bg-blue-500">
							Go to Dashboard
						</Link>
						<Link href="/api/auth/logout" className="p-2 border-2 border-black hover:bg-blue-500">
							Logout
						</Link>
					</div>
				</main>
			</>
		);
	} else {
		return (
			<>
				<Head>
					<title>Team Undefined</title>
					<meta name="description" content="Pharma study app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<header className="sticky top-0 z-50 bg-white shadow-md shadow-slate-900/5">
					<div className="inner-column py-2">
						<nav className="flex justify-between items-center">
							<div>
								<Link href="/">Pharma Study</Link>
							</div>
							<div>
								<ul className="flex flex-row items-center gap-8 text-sm">
									<li>
										<Link href="/api/auth/login" className="">
											Login
										</Link>
									</li>
								</ul>
							</div>
						</nav>
					</div>
				</header>
				<main className="flex-1">
					<section>
						<div className="inner-column">section</div>
					</section>
				</main>
				<footer>
					<div className="inner-column">
						<h2>footer</h2>
					</div>
				</footer>
			</>
		);
	}
}
