import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Sidebar from '@/components/sidebar'
export default function Home() {
  return (
    <>
      <Head>
        <title>Team Undefined</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex justify-center items-center h-screen'>
        <div className='bg-gray-300 w-60 h-80 drop-shadow-lg flex justify-center items-center'>
          <h1>Signing form</h1>
        </div>
      </main>
    </>
  )
}
